CREATE TABLE IF NOT EXISTS conversations (
    id VARCHAR(80) PRIMARY KEY,
    external_user_id VARCHAR(120) NOT NULL,
    title VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_conversations_external_user_id
    ON conversations (external_user_id);

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at
    ON conversations (updated_at);

CREATE TABLE IF NOT EXISTS conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(80) NOT NULL,
    order_index INTEGER NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT,
    attachment_name VARCHAR(255),
    attachment_summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_conversation_messages_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversations (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_conversation_messages_conversation_order
    ON conversation_messages (conversation_id, order_index);
